### PR TITLE
use MemoryStream instead of concat

### PR DESCRIPTION
**Pull request by oliviertassinari**

### CODE REVIEW

**Comment by nolanlawson** [comment]
Can you explain why you made this change? I admit I chose concat-stream because I just found the first thing that worked. Any reason to prefer documenting memorystream instead?

**Comment by oliviertassinari** [comment]
Sure, I want to use `MemoryStream` for exporting to a string and importing to a string.
I still can't make the `load` part works

**Comment by nolanlawson** [comment]
If you're not able to make it work, then is it a good idea to update the README...?

**Comment by oliviertassinari** [comment]
Well, this code works, plus MemoryStream is already documented. I think it's better to reduce the number of dependances

**Comment by oliviertassinari** [comment]
I should update the tests too

**Comment by oliviertassinari** [comment]
test updated.

**Comment by nolanlawson** [comment]
Cool, if the tests are passing with `memorystream`, then I'm definitely +1 for fewer dependencies. Thanks a bunch!

**Comment by oliviertassinari** [comment]
Perfect, I'm gonna try to add a new test `should dump and load using string`

**Comment by nolanlawson** [comment]
Awesome, I'm always happy to have new tests. :)

**Pull request merged**
