### PR TITLE
[string] dump and load

### PR DESCRIPTION
**Pull request by oliviertassinari**
Took me some time to understand how stream works. The `end()` method is the key. May worse to add this to the documentation

### CODE REVIEW

**Comment by oliviertassinari** [comment]
@nolanlawson Here is the same test extended with the reverse function: load.

**Comment by oliviertassinari** [comment]
Any feedbacks?

**Comment by nolanlawson** [comment]
Sorry for the late reply - yes, this looks like a great change, and very helpful. :) I'm happy to merge, but I would kinda prefer to have an additional test rather than change an existing test. (Yes I know you added test behavior, but... paranoia. :wink:)

Anyway I will merge and then add the old test back in as well. I'm seeing a green run in Travis, which means that the test passed. Thanks a bunch!

**Comment by nolanlawson** [comment]
294b8aa8a6c0f2d1262af280427ca68fe78bda77

**Comment by oliviertassinari** [comment]
Make senses! Cool :+1:

**Pull request closed without merging**
